version: "3.2"
services:
  pavlov-shack-server:
    image: powersjk/pavlov-vr-shack-server:latest
    ports:
      - "7000:7000/udp"
      - "7400:7400/udp" 
      - "7777:7777"
      - "7777:7777/udp"
      - "8177:8177"
      - "8177:8177/udp"
      - "${RCON_PORT-9100}:${RCON_PORT-9100}"
    
    environment:
      SERVER_NAME: Phantom's Hell Hole
      RCON_PWD: dontguessthis
      RCON_PORT: ${RCON_PORT-9100}
      UPDATE_SERVER: "True"

    volumes:
      - pavlovData:/home/steam/pavlovserver/Pavlov/Saved

volumes:
  pavlovData:
